![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [85]:
# Import the numpy package under the name np
import numpy as np

import sys

# Print the numpy version and the configuration
print(np.__version__)

1.24.3


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [4]:
# your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [6]:
# your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [8]:
# your code goes here
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [12]:
# your code goes here
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [28]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

np.ones((X.shape[0], X.shape[1]), X.dtype)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [29]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

np.zeros((X.shape[0], X.shape[1]), X.dtype)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [34]:
# your code goes here
np.ones((4, 4), int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [38]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

np.ones((X.shape[0], X.shape[1]), X.dtype)*7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [41]:
# your code goes here
np.eye(3, 3, 0, int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [58]:
# your code goes here
np.random.randint(1, high=11, size=3, dtype=int)

array([2, 2, 6])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [63]:
# your code goes here
np.random.random(size=(3,3,3))

array([[[0.8534947 , 0.54778255, 0.16043615],
        [0.9525712 , 0.01133113, 0.83118661],
        [0.42147773, 0.80225484, 0.54115543]],

       [[0.93725669, 0.20561926, 0.95405775],
        [0.64298941, 0.06185632, 0.9071632 ],
        [0.51256858, 0.10434842, 0.31142637]],

       [[0.1321984 , 0.37507213, 0.75990363],
        [0.17192884, 0.21342563, 0.02210324],
        [0.44663869, 0.31472151, 0.12573858]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [64]:
# your code goes here
X = list(range(100))

np.asarray(X)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [65]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

Y = np.copy(X)

Y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [68]:
# your code goes here
np.arange(10)+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [69]:
# your code goes here
A = np.arange(10)+1

A[A % 2 != 0]

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [76]:
# your code goes here
A = np.arange(10)+1
B = np.flip(A)
B



array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [83]:
# your code goes here
np.random.randint(0, high=9, size=(3,3))

array([[6, 1, 4],
       [8, 5, 5],
       [7, 5, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [86]:
# your code goes here
Z = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])
sys.getsizeof(Z)

188

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [90]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[0]

array([1, 2, 3, 4, 5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [91]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[-1]

array([11, 12, 13, 14, 15])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [93]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

X[0:3]

array([1, 2, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [94]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

X[1:-1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [104]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

X[::-1]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [109]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

X[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [111]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[0]

array([1, 2, 3, 4, 5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [110]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[-1]

array([11, 12, 13, 14, 15])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [112]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[0][0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [113]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[-1][-1]

15

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [114]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[1:-1]

array([[ 6,  7,  8,  9, 10]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [118]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[:2, :2]

array([[1, 2],
       [6, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [122]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

X[-2:, -2:]

array([[ 9, 10],
       [14, 15]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [123]:
# your code goes here
X = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])

np.asfarray(X)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [ ]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [ ]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [ ]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [ ]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [ ]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [ ]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [ ]:
# your code goes here


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [132]:
# your code goes here
X = np.random.normal(size=8)
X
mask = X < 0
(X, mask)

(array([ 2.15252021,  0.12054059,  0.59183766,  0.91038868, -0.86500914,
         0.38332345,  1.15694279,  0.11555976]),
 array([False, False, False, False,  True, False, False, False]))

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [133]:
# your code goes here
X = np.random.normal(size=8)
X
mask = X < 0
X[mask]

array([-0.28392534, -0.04945539, -0.64349056, -0.91536254, -0.47811594])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [136]:
# your code goes here
X = np.random.normal(size=8)*10
X
mask = X > 5

X,X[mask]

(array([ 19.17293769,  19.6579558 ,   2.54682636,  -1.31400585,
        -10.16022315,   9.37300809, -12.61508673,  -3.74318855]),
 array([19.17293769, 19.6579558 ,  9.37300809]))

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [138]:
# your code goes here
X = np.random.normal(size=8)*10
X
mask = X > X.mean()

X,X.mean(),X[mask]

(array([-11.80349697,  -5.69657859,   4.89380867,   7.30159641,
        -10.41559631,   5.31255164,  -4.72079331,   5.60337022]),
 -1.1906422815460824,
 array([4.89380867, 7.30159641, 5.31255164, 5.60337022]))

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [142]:
# your code goes here
X = np.random.randint(0, high=100, size=8)*10
X
mask = (X == 2) | (X == 10)

X,X[mask]

(array([940, 250, 210, 580, 450, 330, 460, 350]), array([], dtype=int32))

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [163]:
# your code goes here
X = np.random.randint(0, high = 3, size=5)

result = True

condition =  lambda y : y != 0

for i in range(X.shape[0]):
    result = condition(X[i]) 
    if result == False:
        break
    else:
        continue
    
X, result

(array([0, 1, 2, 0, 1]), False)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [172]:
# your code goes here
X = np.random.randint(0, high = 3, size=5)

result = False

condition =  lambda y : y == 0

for i in range(X.shape[0]):
    result = condition(X[i]) 
    if result == True:
        break
    else:
        continue
    
X, result

(array([1, 0, 1, 0, 0]), True)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [175]:
# your code goes here
X = np.random.randint(0, high = 8, size=8)
X, X.sum()

(array([5, 3, 5, 7, 2, 7, 4, 0]), 33)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [177]:
# your code goes here
X = np.random.randint(0, high = 8, size=8)
X, X.mean()

(array([2, 2, 7, 7, 0, 3, 0, 5]), 3.25)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [183]:
# your code goes here
X = np.random.randint(0, high = 8, size=(8,8))
X, X.sum(axis=0)

(array([[5, 5, 6, 5, 3, 2, 7, 5],
        [6, 5, 4, 3, 6, 0, 5, 1],
        [1, 3, 6, 4, 4, 5, 4, 5],
        [1, 2, 1, 0, 4, 5, 3, 4],
        [1, 1, 4, 7, 7, 0, 3, 0],
        [7, 7, 4, 4, 2, 7, 7, 6],
        [2, 1, 7, 4, 5, 7, 1, 6],
        [4, 1, 7, 0, 2, 1, 7, 4]]),
 array([27, 25, 39, 27, 33, 27, 37, 31]))

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [185]:
# your code goes here
X = np.random.randint(0, high = 8, size=(8,8))
X, X.sum(axis=1)

(array([[0, 7, 4, 7, 2, 3, 5, 6],
        [4, 1, 6, 1, 3, 4, 1, 4],
        [2, 1, 1, 0, 7, 7, 5, 4],
        [2, 4, 2, 0, 5, 6, 7, 1],
        [4, 4, 5, 2, 7, 1, 1, 5],
        [5, 4, 3, 6, 3, 5, 5, 2],
        [7, 1, 6, 7, 7, 2, 4, 2],
        [4, 3, 2, 1, 4, 6, 3, 0]]),
 array([34, 24, 27, 27, 29, 33, 36, 23]))

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [187]:
# your code goes here
X = np.random.randint(0, high = 8, size=8)
X, X.max()

(array([2, 6, 1, 3, 7, 0, 4, 3]), 7)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)